<a href="https://colab.research.google.com/github/dpenamoya-ops/Visualizaci-nDatosEstilizandoTablasconPython/blob/main/Visualizaci%C3%B3n_de_Datos_estilizando_tablas_con_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Visualization: Estilizando tablas con python**

## **Extracción y preparación de los datos**

In [ ]:
# !pip install pandas==2.0.0

In [1]:
import pandas as pd

print(pd.__version__)

2.2.2

In [2]:
ventas = pd.read_csv('https://gist.githubusercontent.com/ahcamachod/d2efadda3f3833d65da750c64705ac42/raw/80aef6f3bad210d34b67ed85565f039a30e2d9e0/ventas.csv', sep='#')
ventas.head()

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28

In [5]:
ventas.head()

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29
2,2018-06-13,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,49.72,2,11.68
3,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,3255.75,5,-651.15
4,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,76.04,2,4.28

In [4]:
ventas = ventas[['fecha_pedido','modo_envio','nombre_cliente','segmento_cliente','ciudad','provincia','region','departamento','tipo_producto','ventas','cantidad','ganancia']]
ventas.head()

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29
2,2018-06-13,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,49.72,2,11.68
3,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,3255.75,5,-651.15
4,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,76.04,2,4.28

In [6]:
ventas.shape

(8940, 12)

In [7]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.3+ KB

In [12]:
ventas['fecha_pedido'] = pd.to_datetime(ventas['fecha_pedido'],format='%Y-%m-%d')
ventas.head(2)

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29

In [13]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.3+ KB

## Misión 1: Equipo de Ventas

1.   Elemento de lista
2.   Elemento de lista



Necesitamos construir una visualización para indicar los **10 principales clientes por total de ventas**.

Con ello, el equipo de ventas puede pensar en estrategias para mantener a estos clientes comprando en nuestra tienda.

In [16]:
clientes = ventas.groupby(['nombre_cliente'])['ventas'].sum().nlargest(10).copy()
clientes = clientes.reset_index()
clientes

      nombre_cliente    ventas
0    Víctor Carrasco  73370.61
1        Brisa Rojas  68868.11
2       Mateo Vargas  62749.75
3      Vicente Rojas  59544.11
4        Laura Rojas  51398.87
5         Lucía Díaz  48178.99
6   Cristina Barrios  47610.80
7  Alejandro Sánchez  43769.25
8      Pamela Huerta  42354.19
9     Carlos Sánchez  41238.81

In [17]:
# dic = {'nombre_cliente':'Clientes', 'ventas':'Ventas'}
# clientes = clientes.rename(columns=dic)

clientes.columns = ['Clientes','Ventas']
clientes['Ranking'] = clientes.index + 1
clientes.set_index('Ranking', inplace = True)
clientes

                  Clientes    Ventas
Ranking
1          Víctor Carrasco  73370.61
2              Brisa Rojas  68868.11
3             Mateo Vargas  62749.75
4            Vicente Rojas  59544.11
5              Laura Rojas  51398.87
6               Lucía Díaz  48178.99
7         Cristina Barrios  47610.80
8        Alejandro Sánchez  43769.25
9            Pamela Huerta  42354.19
10          Carlos Sánchez  41238.81

In [18]:
estilo = clientes.style
estilo

In [19]:
estilo.format({'Ventas':'{:,.2f}'})
estilo